Quickstart Guide (WIP)
ci4rail/docs pull request #2
Opened 2021-04-23 12:35 UTC by KlausPopp

Moducop Quick Start Guide

2021-04-28 14:37 UTC, MBeer2605 requested changes
generelle Anmerkungen für alle Files: 
- ModuCop statt Moducop
- Im 2.Fall --> ModuCop's statt ModuCops
- Groß- und Kleinschreibung in den Überschriften entsprechend der Regel bearbeiten
- Groß- und Kleinschreibung in den Texten überprüfen. Internet vs. internet... 
- Überschrift 2 hat immer eine Strich drunter... das ist sicher so nicht gewollt. 
- Textpassagen in 'Hochkommas' (z.b. 'nmcli') sind sehr klein, gerade am Satzanfang verschwinden sie fast. 
- Ansprache der Kunden variiert: Manchmal schreibst du "we do something", manchmal "you have to do..." - ich finde die direkte Ansprache "You" gut. 
-

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop.md
> +Here's a quick run-down of the first steps you need to do with the Moducop to use it as an edge computer for edgefarm.
ModuCop bitte im gesamten Doc
(genauso bei EdgeFarm )

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop.md
> +* A Windows or Linux development PC with an ssh client
vielleicht WARUM: .. to establish a secure connection?

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +# Using your local Network as the Internet Connection
zw. Titel und Überschrift sollte eine Zeile frei bleiben oder eine einleitende Textzeile vorhanden sein. So kann man Titel und Überschrift nicht trennen.

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +If your local network provides access to the Internet, you are are almost done. Just check if you could access the Internet.
remove one "are"

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +Let's say you are currently in a lab, but want to prepare Moducop for later use in another network, for example in a vehicle. In the vehicle, you don't have DHCP, so you must configure static IP sett
better: "have to" instead of "must"

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +After reboot, open a new ssh connection using the new configured static IP address. For this to work, the IP address of the development PC and the just configured IP address must be in the same netwo
hier hörts sehr abrupt auf. kann man noch beispielhaft zeigen, wie das geht?

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/lte.md
> +* Insert a Nano SIM Card into the SIM Card slot `TODO: Picture`.
Welchen Sim Slot? Welcher ist per default aktiv?

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/lte.md
> +When the SIM has a pin, and the SIM is not yet unlocked, you will see the SIM state as `locked`:
ist es nicht "If the SIM has a pin..."?
Was ist im Übrigen, wenn nicht?

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/lte.md
> +Now, you need your APN name (e.g. something like `web.vodafone.de`).
zu oft "Now" - mehr variieren..

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/lte.md
> +To ensure that we ping over mobile network, we specify the Wifi device with the `-I` option:
Warum...? Was macht das "I"

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/wifi.md
> +To ensure that we ping over Wifi, we specify the Wifi device with the `-I` option:
das gleiche stand auch bei LTE.... sicher dass das so stimmt?

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/wifi.md
> +You should be able to login as `root` with the standard password `cheesebread`.
haben wir das Passwort nicht schon in den Schritten vorher geändert?

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-to-internet.md
> +In the [previous chapter]({{ '/quick-start-guide/moducop/connect-to-terminal' | relative_url }}), you connected Moducop with your local network and you have connection to Moducops Linux terminal from
and established connection to ModuCop's Linux terminal from...

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-to-terminal.md
> +In this section, you will connect your development PC with the Moducop Linux terminal, to configure basic parameters, such as the way to connect Moducop with the Internet.
kein Komma nach terminal

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-to-terminal.md
> +* Local network your Developer PC attached. Network with DHCP support
hier passt was vom Satz nicht... 
Developer PC attached to local network?
Network with DHCP support

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-to-terminal.md
> +Enter `cheesebread` as the password. While you entering the password, you will not see any feedback on the console. This is normal.
Das ist wohl ein Feature von dem PuTTY. aber ich finde das sehr unkomfortable, dass man nicht sieht, ob und wie viel mal schon getippt hat.

2021-04-28 14:37 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/no-starter-kit-bom.md
> +* Wifi Antenna (If you want to use LTE)
if you want to use Wifi

2021-04-29 06:13 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop.md
> +Here's a quick run-down of the first steps you need to do with the Moducop to use it as an edge computer for edgefarm.
Done

2021-04-29 06:15 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop.md
> +* A Windows or Linux development PC with an ssh client
added: to be able to login into ModuCop with a secure connection.

2021-04-29 06:15 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +# Using your local Network as the Internet Connection
Bitte Issue an Heike

2021-04-29 06:15 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +If your local network provides access to the Internet, you are are almost done. Just check if you could access the Internet.
done

2021-04-29 06:16 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +Let's say you are currently in a lab, but want to prepare Moducop for later use in another network, for example in a vehicle. In the vehicle, you don't have DHCP, so you must configure static IP sett
Done

2021-04-29 06:55 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/lte.md
> +* Insert a Nano SIM Card into the SIM Card slot `TODO: Picture`.
Das weiß ich noch nicht. Können wir erst sagen, wenn wir CPU layout 1 haben

2021-04-29 13:17 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +After reboot, open a new ssh connection using the new configured static IP address. For this to work, the IP address of the development PC and the just configured IP address must be in the same netwo
Added animated GIF to show how to configure static IP under windows. For Linux, it heavily depends on the distribution. I think, we can expect that a linux user knows how to do it

2021-04-29 13:25 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/lte.md
> +When the SIM has a pin, and the SIM is not yet unlocked, you will see the SIM state as `locked`:
Ok, added a sentence "If the SIM is already unlocked, you'll see `state: registered`..."

2021-04-29 13:26 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/lte.md
> +Now, you need your APN name (e.g. something like `web.vodafone.de`).
Done

2021-04-29 13:28 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/lte.md
> +To ensure that we ping over mobile network, we specify the Wifi device with the `-I` option:
Added: This ensures that the ping uses the LTE interface and not your local Ethernet for the Internet access.

2021-04-29 13:29 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/wifi.md
> +To ensure that we ping over Wifi, we specify the Wifi device with the `-I` option:
Corrected.

2021-04-29 13:33 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/wifi.md
> +You should be able to login as `root` with the standard password `cheesebread`.
Good catch! Changed to "password you assigned in this step"

2021-04-29 13:36 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-to-internet.md
> +In the [previous chapter]({{ '/quick-start-guide/moducop/connect-to-terminal' | relative_url }}), you connected Moducop with your local network and you have connection to Moducops Linux terminal from
Done

2021-04-29 13:37 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-to-terminal.md
> +In this section, you will connect your development PC with the Moducop Linux terminal, to configure basic parameters, such as the way to connect Moducop with the Internet.
Done

2021-04-29 13:39 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-to-terminal.md
> +* Local network your Developer PC attached. Network with DHCP support
Changed

2021-04-29 13:39 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/connect-to-terminal.md
> +Enter `cheesebread` as the password. While you entering the password, you will not see any feedback on the console. This is normal.
It's not specific to putty. Its a general behavior of ssh. Cannot be changed

2021-04-29 13:40 UTC, KlausPopp commented on docs/user-docs/_quick-start-guide/moducop/no-starter-kit-bom.md
> +* Wifi Antenna (If you want to use LTE)
Changed

2021-04-29 13:57 UTC, KlausPopp commented
> 
> 
> generelle Anmerkungen für alle Files:
> 
>     * ModuCop statt Moducop
> 
>     * Im 2.Fall --> ModuCop's statt ModuCops
> 
>     * Groß- und Kleinschreibung in den Überschriften entsprechend der Regel bearbeiten
> 
>     * Groß- und Kleinschreibung in den Texten überprüfen. Internet vs. internet...
> 
>     * Überschrift 2 hat immer eine Strich drunter... das ist sicher so nicht gewollt.
> 
>     * Textpassagen in 'Hochkommas' (z.b. 'nmcli') sind sehr klein, gerade am Satzanfang verschwinden sie fast.
> 
>     * Ansprache der Kunden variiert: Manchmal schreibst du "we do something", manchmal "you have to do..." - ich finde die direkte Ansprache "You" gut.

Please create isssue for 
"Überschrift 2 hat immer eine Strich drunter"
"Textpassagen in 'Hochkommas' (z.b. 'nmcli') sind sehr klein".
Everything else considered

2021-04-30 06:26 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/moducop/connect-internet/ethernet.md
> +# Using your local Network as the Internet Connection
Ich habe versch. Issues erstellt.

2021-04-30 06:28 UTC, MBeer2605 approved these changes

2021-04-30 07:44 UTC, KlausPopp commented
Initial version of Moducop Quickstart

2021-04-30 07:44 UTC, merged