Iou WIP
ci4rail/docs pull request #30
Opened 2022-03-17 13:26 UTC by KlausPopp

Basic docs for IOU01 and MIO01

2022-03-21 11:36 UTC, MBeer2605 requested changes
super doku. 
grundsätzlich sind noch nicht alle seiten in der Side-Bar
zusätzlich: die Sidebar bleibt nicht aufgeklappt, wenn man auf einer tieferen Seite ist - Das ist bei ModuCop anders und sollte sich auch so verhalten. 

Auch: ModuSio fehlt noch die Beschreibung für das Service Interface.

2022-03-21 11:36 UTC, MBeer2605 commented on docs/user-docs/_edge-solutions/io4edge.md
> +io4edge is the family name for I/O modules that are connected to the host via network (Ethernet, WLAN, Ethernet over USB). All io4edge Devices share some common functionality such as.
Devices klein

2022-03-21 11:36 UTC, MBeer2605 commented on docs/user-docs/_edge-solutions/io4edge/networking.md
> +title: io4edge Networking
Fehlt noch in der Side bar

2022-03-21 11:36 UTC, MBeer2605 commented on docs/user-docs/_edge-solutions/io4edge/networking.md
> +However, this address is only used as long no application specific `device-id` is set in the module. It is adisable to change the `device-id` to an application defined name, such as `axle-sensor-left
typo advisable oder We recommend

2022-03-21 11:36 UTC, MBeer2605 commented on docs/user-docs/_edge-solutions/io4edge/management.md
> +All io4edge Devices support Device Management over Network for
devices klein

2022-03-21 13:54 UTC, KlausPopp commented on docs/user-docs/_edge-solutions/modusio.md
> +{% include pages_table.html headline_link="IO-Module" type="modusio-module" %}
War im excerpt von mio01.md falsch

2022-03-21 13:57 UTC, KlausPopp commented on docs/user-docs/_edge-solutions/modusio/mio01.md
> +{{ page.product_name }} is an Io4Edge Device, and therefore supports the features common to all Io4Edge devices.
ok

2022-03-21 13:58 UTC, KlausPopp commented on docs/user-docs/_edge-solutions/moducop/io-modules/iou01.md
> +{{ page.product_name }} is a Binary & analogue input/output extension unit for edge applications in rail & busses.
ok

2022-03-21 13:58 UTC, KlausPopp commented on docs/_includes/content/io4edge/iou01-front/quick-start-guide.md
> +* A Laboratory Power Supply capable of supplying 5V..24V/200mA.
ok

2022-03-21 14:05 UTC, KlausPopp commented on docs/_includes/content/io4edge/iou01-front/quick-start-guide.md
> +Connect the `CI` and `CO` pins to your laboratory power supply which is set to a voltage of 24V (up to 110V).
ok

2022-03-21 14:16 UTC, KlausPopp commented on docs/_includes/content/io4edge/analogintypea/detailed-description.md
> +To access the Analog Inputs, create a *Client* `c`. Pass as address either a service address or an ip address with port. Examples:
create a *Client* and save it to the variable `c`

2022-03-22 07:06 UTC, MBeer2605 approved these changes

2022-03-23 08:06 UTC, MBeer2605 approved these changes

2022-03-25 08:32 UTC, merged