Iou04 and MIO04 Docs
ci4rail/docs pull request #31
Opened 2022-08-05 09:05 UTC by KlausPopp

2022-08-05 15:00 UTC, MBeer2605 requested changes
Wirklich super geworden. 
Hab nix auszusetzen ausser der Link zur Next Page.. und halt das CAN Kapitel. !!! TOP

2022-08-05 15:00 UTC, MBeer2605 commented on docs/_includes/content/modusio/quick-start-guide.md
> +ModuSio devices are Class 2 (3,84–6,49 W) PoE powered devices. Connect the ModuSio Device to a PoE source that can supply class 2 devices. ModuSios expect the PoE power as phantom power, i.e. using t
sind wir wirklich Class 2 - nicht 1?

2022-08-05 15:00 UTC, MBeer2605 commented on docs/user-docs/_edge-solutions/modusio/mio04/quick-start-guide.md
> +custom_next: /edge-solutions/modusio/mio01/detailed-description/
Custom Next Pages leads to MIO01, not to MIO04 Detailed Description

2022-08-05 15:00 UTC, MBeer2605 commented on docs/user-docs/_edge-solutions/modusio/mio04/detailed-description.md
> +Some further content.
ist nur ein Platzhalter oder? Muss noch raus.

2022-08-05 15:00 UTC, MBeer2605 commented on docs/_includes/content/io4edge/iou04-front/detailed-description.md
> +The {{ page.product_name }} has one CANBus interfaces, labelled `CAN`.
klar , ab hier fehlts noch...

2022-08-05 15:00 UTC, MBeer2605 commented on docs/_includes/content/io4edge/ttynvt/detailed-description.md
> +**WARNING** pyserial with RFC2217 does not support the proprietary extension to set the COM port into half duplex mode. Therefore half-duplex mode is not supported.
Wäre für mich mehr eine Note... Warning ist wirklich Security, wie oben.

2022-08-05 15:00 UTC, MBeer2605 commented on docs/_includes/content/io4edge/canl2/detailed-description.md
> +### Features
noch alt. IOU01

2022-08-12 09:43 UTC, KlausPopp commented on docs/user-docs/_edge-solutions/modusio/mio04/quick-start-guide.md
> +custom_next: /edge-solutions/modusio/mio01/detailed-description/
Done

2022-08-12 09:44 UTC, merged