Add IOU03, MIO03 and IOU07 docs
ci4rail/docs pull request #35
Opened 2022-10-28 13:41 UTC by KlausPopp

2022-10-31 13:28 UTC, FranziskaKnoedtel commented
In /edge-solutions/modusio/mio03/quick-start-guide/#demo-software the example name should be streamDump not stream.

2022-10-31 13:35 UTC, FranziskaKnoedtel commented
edge-solutions/modusio/mio03/quick-start-guide/#select-wifi-as-host-interface: We should be consistent with form of placeholder. I think we always put them between < and >.

2022-10-31 13:42 UTC, FranziskaKnoedtel commented
In edge-solutions/modusio/config-console/#LinuxIdterminal: Was this todo forgotten?

2022-10-31 15:10 UTC, FranziskaKnoedtel commented
In edge-solutions/modusio/mio03/detailed-description/#using-the-io4edge-api-to-access-can-function: The link "described here" is dead.

2022-10-31 15:15 UTC, FranziskaKnoedtel commented
In edge-solutions/modusio/mio03/detailed-description/#bus-configuration: there are two ways to store the can-config persistently: Via io4edge-cli and via service interface.

2022-10-31 15:21 UTC, FranziskaKnoedtel commented
In edge-solutions/modusio/mio03/detailed-description/#bus-configuration: Point out that it is mandatory to set the listen-only mode, to prevent errors, but in future the mode will be fix for the device.

2022-11-02 12:55 UTC, FranziskaKnoedtel commented
In edge-solutions/modusio/mio04/quick-start-guide/#interface-demos:  Quick start guide of MIO03 and MIO04 are in a different form. MIO04 docu links to the serial port and CAN instructions, MIO03 docu has the MVB and CAN instructions on one page.

2022-11-02 14:34 UTC, FranziskaKnoedtel commented
In edge-solutions/modusio/mio03/quick-start-guide/#create-a-socketcan-instance: The description of the vcan interface name is a bit complicated. You are using the terms service name and interface name for the same. As long as we do not have two can interfaces on one io-module, I would prefer to use the term device id, because it is clearer for the customer what is meant, as it is described some points above how to set the device id.

2022-11-02 14:40 UTC, FranziskaKnoedtel commented
In edge-solutions/modusio/mio03/quick-start-guide/#create-a-socketcan-instance: Mention that two MIOs with the same uuid ending have the same vcan interface name because the default device ID consists of model and uuid. In this case, the customer should set the device ID so that the vcan interface name is unique.

2022-11-02 15:02 UTC, FranziskaKnoedtel commented
> In edge-solutions/modusio/mio03/quick-start-guide/#create-a-socketcan-instance: Mention that two MIOs with the same uuid ending have the same vcan interface name because the default device ID consists of model and uuid. In this case, the customer should set the device ID so that the vcan interface name is unique.

Mention also that afterwards the socketcan-io4edge-runner or the moducop has to be restarted.

2022-11-02 15:29 UTC, FranziskaKnoedtel commented
In edge-solutions/modusio/mio04/detailed-description/#using-ttynvt: major-number description: The major number identifies the driver associated with the device. Select for the ttynvt driver a number that is not yet in use in your system.

2022-11-03 08:18 UTC, FranziskaKnoedtel commented
In edge-solutions/io4edge/addressing/#ip-address-assignment: The MIOs provide the option to set a static ip address.

2022-11-03 08:23 UTC, FranziskaKnoedtel commented
In edge-solutions/io4edge/addressing/#addressing-moducop-io-modules: So when you have an IOU01 module in slot 1 ...

2022-11-03 16:19 UTC, FranziskaKnoedtel requested changes
Review not complete. Preliminary result.

2022-11-03 19:39 UTC, KlausPopp commented on docs/_includes/content/io4edge/iou03-front/can-config-connect.md
> +
Because its a little different (listen only on MIO3), other drawing. Its not work to factor this out for 36 lines

2022-11-04 14:43 UTC, FranziskaKnoedtel requested changes
In edge-solutions/moducop/io-modules/iou07/detailed-description/#reading-inputs-and-channel-diagnostics: diag is a repeated bit field

2022-11-07 08:38 UTC, FranziskaKnoedtel approved these changes

2022-11-07 08:47 UTC, merged