sio03 added
ci4rail/docs pull request #60
Opened 2024-06-07 12:36 UTC by MBeer2605

added SIO03, modified SIO02

2024-06-10 13:57 UTC, KlausPopp requested changes

2024-06-10 13:57 UTC, KlausPopp commented on docs/user-docs/_lyve/lyve-tracelets.md
Remove (coming soon) from SIO03

2024-06-10 13:57 UTC, KlausPopp commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +| Firmware update                        | Via USB, WLAN |
via LAN

2024-06-10 13:57 UTC, KlausPopp commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +| Management                             | Via io4edge protocol, see https://docs.ci4rail.com/edge-solutions/io4edge/ |
Use link [io4edge protocol]({{ '/edge-solutions/io4edge' | relative_url }})

2024-06-10 13:57 UTC, KlausPopp commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +* Wheeltic Input
Wheeltick

2024-06-10 13:57 UTC, KlausPopp commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +![Lyve Tracelet]({{ '/user-docs/images/lyve/SIO02_model_halterung.png' | relative_url }})
Drawings show SIO02

2024-06-10 15:30 UTC, MBeer2605 commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +![Lyve Tracelet]({{ '/user-docs/images/lyve/SIO02_model_halterung.png' | relative_url }})
will do a comment, that equal for SIO02 and SIO03 - no specific drawings will be done

2024-06-10 15:31 UTC, MBeer2605 commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +| Firmware update                        | Via USB, WLAN |
done

2024-06-10 15:32 UTC, MBeer2605 commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +| Management                             | Via io4edge protocol, see https://docs.ci4rail.com/edge-solutions/io4edge/ |
done

2024-06-10 15:33 UTC, MBeer2605 commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +| Firmware update                        | Via USB, WLAN |
done

2024-06-10 15:33 UTC, MBeer2605 commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +| Management                             | Via io4edge protocol, see https://docs.ci4rail.com/edge-solutions/io4edge/ |
done

2024-06-10 15:33 UTC, MBeer2605 commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +* Wheeltic Input
done

2024-06-10 15:34 UTC, MBeer2605 commented on docs/user-docs/_lyve/lyve-tracelets/sio03/detailed-description.md
> +* Wheeltic Input
done

2024-06-10 15:40 UTC, MBeer2605 commented on docs/user-docs/_lyve/lyve-tracelets.md
done

2024-06-11 06:05 UTC, KlausPopp approved these changes

2024-06-11 06:06 UTC, MBeer2605 commented
SIO03 Branch merged into main

2024-06-11 06:06 UTC, merged