Added Simulator quickstart
ci4rail/docs pull request #8
Opened 2021-05-06 12:34 UTC by siredmar

2021-05-06 15:02 UTC, MBeer2605 requested changes
Hallo Armin, 
für mich fehlt ganz oft der Kontext, warum machen wir den nächsten Schritt. 
nimm den Kunden bitte mehr an die Hand. 
mir ist oft unklar, wo wir gerade sind. 
- cmd line im Pfad, in dem ich edgefarm cli ausführe
- cmd line in dem ich docker ausführe) ich hab jetzt nach der Anleitung drei shellss offen und weis nie, wo ich hin soll. 

Ich finde die Windows Installation für Docker unglaublich kompliziert. Ich fürchte, da verlieren wir einige (Ich denke an Logomotive) - lass uns drüber reden, wie es vielleicht einfacher geht.

2021-05-07 08:03 UTC, KairaMiu requested changes
Please see [Naming Conventions](http://localhost:4000/how-to-write-documentation/#naming-conventions) for image name convention (use only small letters and use `-` to separate them)

2021-05-07 08:22 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +# Download `edgefarm-cli`
This is the behavior when using `target="_blank"`
Opening in the same window is standard. Please read https://css-tricks.com/use-target_blank/ and tell me if you still want this.

2021-05-07 08:29 UTC, siredmar commented on docs/_data/sidebars/quick-start-guide.yml
> +              url: /quick-start-guide/edgefarm/simulator/deploy-demo-app/
Using landing page.

2021-05-07 08:34 UTC, siredmar commented on docs/_data/sidebars/quick-start-guide.yml
> +              url: /quick-start-guide/edgefarm/simulator/deploy-demo-app/
naming of images fixed.

2021-05-07 08:35 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +## Usage of `edgefarm-cli`
fixed.

2021-05-07 08:41 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator.md
> +![Basic Train Simulator Demo architecture]({{ 'user-docs/images/edgefarm/simulator/demo_arch.png' | relative_url }} "Basic Train Simulator Demo architecture"){: style="width: 50%"}
done.

2021-05-07 08:41 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator.md
> +Once the simulator is up and running it sends simulated data to an MQTT broker. The application module `alm-mqtt-module` running on the device listens to the MQTT topics from the simulator. It then r
done.

2021-05-07 08:48 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/windows.md
> +Once WSL2 with Ubuntu 20.04 is installed, continue with the [Linux setup instructions](/quick-start-guide/edgefarm/simulator/prerequisites/linux/).
not relevant anymore.

2021-05-07 08:50 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/windows.md
> +custom_next: /quick-start-guide/edgefarm/simulator/start-simulator/
yes

2021-05-07 08:50 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/linux.md
> +See this section for troubleshooting.
ok

2021-05-07 08:53 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +This chapter describes how to get the `Train Simulator` up and running.
ok

2021-05-07 09:03 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +![Running simulation]({{ 'user-docs/images/edgefarm/simulator/simulation_running.png' | relative_url }} "Running simulation"){: style="width: 75%"}
fixed.

2021-05-07 09:06 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +$ docker run -it --rm efrecon/mqtt-client sub -h `docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'` -t "simulation/#" -v
alright.

2021-05-07 09:07 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +If some values come in abort with `Ctrl+C`.
fixed.

2021-05-07 09:13 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/windows.md
> +# Setup
fixed.

2021-05-07 09:14 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/windows.md
> +Using WSL installing the Linux way or a standard Windows Installation process.
fixed.

2021-05-07 09:15 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/windows.md
> +At this point you have to decide which way you want to go. Either the regular installation or with 'Windows Subsystem for Linux'.
fixed.

2021-05-07 09:18 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/windows.md
> +For further information see the official Docker documentation on [how to install Docker Desktop on Windows](https://docs.docker.com/docker-for-windows/install/).
fixed.

2021-05-07 09:18 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +The following tools must be installed. See the [previous section](/quick-start-guide/edgefarm/simulator/prerequisites/) for assistance.
fixed.

2021-05-07 09:19 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +Make sure that Docker Desktop is running.
fixed in docker Desktop installation

2021-05-07 09:27 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +  docker-compose up -d
Warning is ok. Noted when you are done.

2021-05-07 09:27 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +Next go to Node-Red's web UI [http://localhost:1880](http://localhost:1880) to start the simulation. Click on the blue control right next to the `start` node.
fixed problems regarding git and line endings

2021-05-07 09:31 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/deploy-demo-app.md
> +
more context? done.

2021-05-07 09:32 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/deploy-demo-app.md
> +
added.

2021-05-07 09:58 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/deploy-demo-app.md
> +This example shows how this might look like:
No highliting in formatting block possible. Added line number to change.

2021-05-07 09:59 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/deploy-demo-app.md
> +
fixed.

2021-05-07 10:30 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/deploy-demo-app.md
> +$ edgefarm alm apply -f manifest.yaml
This is because edgefarm is not in your path variable.
Added description in basic usage

2021-05-07 10:47 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +First login to your user using the login command
fixed with path variables.

2021-05-07 10:47 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +```
fixed.

2021-05-07 10:47 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +This chapter shows the basic usage of the edgefarm-cli to interact with the edgefarm services.
done.

2021-05-07 10:48 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +To apply an application manifest file use.
this is not best practice.

2021-05-07 10:48 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +$ edgefarm alm apply -f <manifest-file>
added example

2021-05-07 10:49 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator.md
> +The `Train Simulator Demo` simulates sensors and bus systems normally found in trains.
fixed.

2021-05-07 10:50 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites.md
> +In order to run the `Train Simulator Demo` you have to satisfy some prerequisites on the machine that acutally runs the simulatior.
fixed.

2021-05-07 10:50 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites.md
> +Tools needed:
added.

2021-05-07 10:51 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/windows.md
> +There are two ways to run the satisfy the prerequisits needed for the `Train Simulator`.
fixed.

2021-05-07 10:51 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/deploy-demo-app.md
> +The Train Simulator Demo application is the part thar runs on the ModuCop.
fixed.

2021-05-07 18:08 UTC, MBeer2605 requested changes
hab immer noch einen Bug.

2021-05-07 18:08 UTC, MBeer2605 commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/deploy-demo-app.md
> +View the logs of the `train-simulator_edge-demo -f` container by running `docker logs`. The output should look similar to this.
To check, whether everything is connected properly and running, view the logs of ...

2021-05-10 06:40 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +$ docker run -it --rm efrecon/mqtt-client sub -h `docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'` -t "simulation/#" -v
You are right. This command does not seem to work on windows... :-1:

2021-05-10 06:49 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/start-simulator.md
> +# Testing the Simulator
I hope its more clear now

2021-05-10 06:52 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/deploy-demo-app.md
> +View the logs of the `train-simulator_edge-demo -f` container by running `docker logs`. The output should look similar to this.
fixed.

2021-05-10 06:52 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/simulator/prerequisites/windows.md
> +If you need further information please consult the official Docker documentation on [how to install Docker Desktop on Windows](https://docs.docker.com/docker-for-windows/install/).
fixed.

2021-05-10 06:53 UTC, siredmar commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +Verify that your PATH variable settings have been successfully by executing the EdgeFarm CLI.
fixed.

2021-05-10 15:35 UTC, KairaMiu requested changes

2021-05-10 15:35 UTC, KairaMiu commented on docs/user-docs/_quick-start-guide/edgefarm/basic-functions.md
> +$ echo PATH="$PATH:~/bin" >> .bashrc
```
$ echo PATH="$PATH:~/bin" >> ~/.bashrc
$ source ~/.bashrc
```

2021-05-11 06:39 UTC, merged